services:
  postgres:
    container_name: ftiness-app-api
    image: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ftiness-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  backend:
    build: .
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start:prod"]
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:docker@postgres:5432/ftiness-api
